### ISSUE TITLE
Fatal error when recursion limit is reached

### ISSUE THREAD

**Issue by pakshuang** [NUSSOC/glide#1]
When the max call stack size is exceeded, the console can no longer be used.

Here, I ran a function (now commented) that caused the max call stack size to be exceeded. Then, I defined a new function that did not exceed the max call stack size. When I ran the script, it would not run and the page had to be reloaded.

![image](https://user-images.githubusercontent.com/81917538/229581274-69bd9659-0697-41e3-8ab5-8fee47362fc2.png)

**Comment by purfectliterature** [comment]
Thanks for catching this!

This issue was raised here https://github.com/pyodide/pyodide/issues/951. Basically, seems like the default recursion limit is too high, such that the browser cannot keep up. There was a patch that resulted in that conversation to fatally terminate Pyodide to prevent code execution on potentially invalid state of the VM, hence the last line of the error message in your screenshot.

The recursion error was actually bubbled into JavaScript's `RangeError`, and contrary to what we see in IDLE, we don't see Python's native `RecursionError`. We can catch the `RangeError` in JavaScript and automatically restart a new instance of Pyodide safely.

Another alternative is to manually set the recursion limit, e.g.,
```py
import sys
sys.setrecursionlimit(500)
```

If the recursion limit is actually reached, then we will see `RecursionError`. In my computer, any limit beyond 410 will no longer be caught. Some computers can handle up to 500.

I feel like whether or not this recursion limit is set is up for deciding. The correct patch is to actually catch when Pyodide fatally dies and respawn. This way, we don't risk some computers from potentially not reaching our arbitrary recursion limit.

Fixed as of d1eb634542a46a694b661b3bb4829ab55a7ddf36. This patch will be available in the next release.

**Comment by pakshuang** [comment]
Thanks! Could the message also remind the user to save their work first?
